In [1]:
import os
import numpy as np
import pandas as pd

from process_audio import extract_audio, preprocess_audio
from process_video import preprocess_video_every_3_seconds

from tensorflow.keras.models import load_model


import numpy as np

In [5]:
video_path = "../pang.mp4"

In [6]:
video = preprocess_video_every_3_seconds(video_path, (256, 256), 3)

In [7]:
video.shape

(203, 9, 256, 256, 1)

In [8]:
video_model = load_model("../video_model.h5")

In [14]:
res = []

for data in video:
    reshaped_input = np.reshape(data, (-1, 9, 256, 256, 1))
    pred = video_model.predict(reshaped_input)
    res.append(pred)

res[:5]

1/1 [==============================] - 0s 15ms/step


[array([[0.14531963, 0.5953397 , 0.25934064]], dtype=float32),
 array([[0.14531963, 0.5953397 , 0.25934064]], dtype=float32),
 array([[0.14531963, 0.5953397 , 0.25934064]], dtype=float32),
 array([[0.14531963, 0.5953397 , 0.25934064]], dtype=float32),
 array([[0.14531963, 0.5953397 , 0.25934064]], dtype=float32)]

In [15]:
final_predictions = np.argmax(res, axis=1)
final_predictions

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0,